import { GeistSans } from "geist/font";
import type { Metadata } from "next";
import { Toaster } from "ui/components/ui/toaster";
import { cn } from "ui/lib/utils";
import "ui/styles/globals.css";

export const metadata: Metadata = {
  title: "VATMENA Training HQ",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={cn("dark overscroll-none", GeistSans.className)}>
        <div className="flex flex-col h-screen overflow-hidden">{children}</div>
        <Toaster />
      </body>
    </html>
  );
}
