import type { Metadata } from "next";
import "ui/styles/globals.css";
import { Toaster } from "ui/components/ui/toaster";

export const metadata: Metadata = {
	title: "VATMENA Training HQ",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: {
	children: React.ReactNode;
}) {
	return (
		<html lang="en" className="dark">
			<body className="overscroll-none">
				<div className="flex h-screen w-full grow flex-col">{children}</div>
				<Toaster />
			</body>
		</html>
	);
}
